# Generated by Django 2.2.10 on 2020-03-04 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
